<template>
  <article class="report page-enter">
    <div class="report-toolbar"><span class="eyebrow">SOUL THINKER · 上班状态测试</span><button class="text-button" @click="$emit('edit')">改答案</button></div>
    <section class="report-hero"><div class="hero-copy"><span class="hero-kicker">{{ results.evaluatedAt }}</span><p class="hero-overline">这阵子的你</p><h1>{{ results.profile.name }}</h1><p class="hero-line">{{ results.profile.line }}</p><p class="hero-summary">{{ results.summary }}</p><div class="hero-tags"><span>{{ results.focus.kind==='steady'?results.focus.answerLabel+' · '+results.focus.displayAnswer:'最想改变 · '+results.focus.name }}</span><span v-if="results.strength && results.focus.kind!=='steady'">相对舒服 · {{ results.strength.name }}</span></div></div><div class="hero-note"><img src="/soul-thinker-logo-transparent.png" alt=""></div></section>
    <nav class="report-nav" aria-label="结果内容"><a href="#map">六项分数 <span aria-hidden="true">↓</span></a><a href="#detail">你最在意的 <span aria-hidden="true">↓</span></a><a href="#next">可以试试的事 <span aria-hidden="true">↓</span></a></nav>
    <section v-if="results.alerts.length" class="alert-section"><h2>有件事别轻轻带过</h2><p v-for="item in results.alerts" :key="item.questionId">{{ item.text }}</p></section>
    <section id="map" class="report-section"><div class="section-heading"><div><span class="section-kicker">01 / 六项分数</span><h2>{{ results.focus.kind==='steady'?'这六项，目前都挺顺':'哪儿还行，哪儿最累' }}</h2></div></div><div class="work-grid"><div class="paper radar-card"><RadarChart :data="results.dimensions.map(d=>({label:d.short,value:d.score}))"/></div><div class="paper dimension-list"><div v-for="dim in results.dimensions" :key="dim.id" class="dimension-row"><div class="dimension-title"><h3>{{ dim.name }}</h3><b>{{ dim.score }}<small> / 100</small></b></div><div class="score-track" role="meter" :aria-label="dim.name" :aria-valuenow="dim.score" aria-valuemin="0" aria-valuemax="100"><span :style="{width:dim.score+'%',background:dim.color}"></span></div><p class="dimension-description">{{ dim.hint }}</p></div></div></div><p class="chart-note">越往外，说明这一项你过得越舒服。六项分数只用来比较自己的感受，没有“及格线”。</p></section>
    <section id="detail" class="report-section"><div class="section-heading"><div><span class="section-kicker">02 / 你最在意的</span><h2>{{ results.focus.kind==='steady'?'现在这样，哪里让你觉得好':'让你难受的，和你舍不得的' }}</h2></div></div><div class="detail-grid" :class="{single:results.focus.kind==='steady'}"><div class="paper detail-card focus-card"><span class="detail-kicker">{{ results.focus.kind==='steady'?'你想留住':'你最想改变' }}</span><h3>{{ results.focus.name }}</h3><p>{{ results.focus.note }}</p><blockquote><span class="follow-answer-label">{{ results.focus.answerLabel }}</span><span>“{{ results.focus.displayAnswer }}”</span></blockquote><p v-if="results.focus.kind==='steady'" class="priority-note">你还选了：{{ results.priority }}</p><button class="text-button" @click="$emit('edit',results.focus.questionId)">这题我想改</button></div><div v-if="results.focus.kind!=='steady'" class="paper detail-card"><span class="detail-kicker">你还想保住</span><h3>{{ results.priority }}</h3><p v-if="results.strength">另外，「{{ results.strength.name }}」这一项你给的分也不低。它是这份工作里还让你舒服的地方。</p><p v-else>六项里暂时没有哪一项让你觉得稳。这时候不用硬找好处。</p></div></div></section>
    <section id="next" class="report-section"><div class="section-heading"><div><span class="section-kicker">03 / 接下来可以试试</span><h2>{{ results.focus.kind==='steady'?'把现在过得好的地方留住':'先试一步，再看有没有变化' }}</h2></div></div><div class="action-list"><div v-for="(action,i) in results.actions" :key="action.id" class="paper action-card"><span class="action-index">{{ String(i+1).padStart(2,'0') }}</span><div><h3>{{ action.title }}</h3><p>{{ action.text }}</p></div></div></div></section>
    <section class="report-export"><div><h3>过阵子再看，可能又不一样了。</h3><p class="small muted">分享图会显示你填的称呼；不填也没关系。</p></div><div class="export-buttons"><button class="secondary" @click="copyResult">复制文字</button><button class="primary" @click="$emit('share')">做张分享图 →</button></div></section>
    <details class="report-method"><summary>分数是怎么算的？</summary><p>前24题分成六个维度，每个维度4题。每题按0—3分计，四题得分按比例换算为0—100分。分数越高，说明你在这一项上的感受越好。结果类型由电量、做事的自主空间和工作中的收获三方面共同决定；最后两题会补充你最在意的事，并影响结果重点和行动建议。本工具不是科学量表，旨在帮你理清感受。</p></details>
  </article>
</template>
<script setup>
import RadarChart from './RadarChart.vue'
const props=defineProps({results:{type:Object,required:true}})
const emit=defineEmits(['edit','share','notice'])
const copyResult=async()=>{const r=props.results;const answer=`${r.focus.answerLabel}：“${r.focus.displayAnswer}”`;const focus=r.focus.kind==='steady'?answer:`最想改变：${r.focus.name}\n${answer}`;const priority=r.focus.kind==='steady'?'':`\n想保住：${r.priority}`;const actions=r.actions.map((action,index)=>`${index+1}. ${action.title}：${action.text}`).join('\n');const text=`Soul Thinker · 上班状态测试\n${r.profile.name}\n${r.profile.line}\n${r.summary}\n${focus}${priority}\n\n可以试试：\n${actions}`;try{await navigator.clipboard.writeText(text);emit('notice','已复制')}catch{emit('notice','没复制成功，试试分享图吧')}}
</script>
